import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AuthContextProvider} from "@/modules/auth/AuthContextProvider";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Another To-Do list app",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {

    return (
        <html lang="en">
        <body className={"bg-[#1C1C21] text-white"}>
        <AuthContextProvider>{children}</AuthContextProvider>
        </body>
        </html>
    );
}
